name: CD for Deployment 
on :
    push:
      branches:
        - main
jobs:
    Continuous-Deployment:
        runs-on: ubuntu-latest

        steps: 
          - name: deploy
            env: 
                SSH_KEY: ${{secrets.SSH_KEY}}
                HOST: ${{secrets.HOST}}
                USER: ${{secrets.USER}}

            run: |
              mkdir -p ~/.ssh
              eval "$(ssh-agent -s)"
              echo "$SSH_KEY" | tr -d '\r' | ssh-add -
              ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts
              ssh  "$USER$HOST" << 'EOF'
                  set -e 
                  ls 
                  cd Deploy_monorepo
                  git checkout main
                  git pull origin main
                  pnpm install
                  pm2 restart all || pm2 restart fe-server || pm2 restart http_server || pm3 restart ws_server
                EOF


      
